# Generated by Django 5.2.6 on 2025-12-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="client",
        ),
        migrations.RemoveField(
            model_name="serviceorder",
            name="client",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="client",
        ),
        migrations.RemoveField(
            model_name="servicelead",
            name="client",
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Cached client email for display",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Client ID from main auth service",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_name",
            field=models.CharField(
                default="", help_text="Cached client name for display", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="client_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Cached client email for display",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Client ID from main auth service",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="client_name",
            field=models.CharField(
                default="", help_text="Cached client name for display", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="servicelead",
            name="client_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Cached client email for display",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="servicelead",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Client ID from main auth service",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="servicelead",
            name="client_name",
            field=models.CharField(
                default="", help_text="Cached client name for display", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="client_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Cached client email for display",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Client ID from main auth service",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="client_name",
            field=models.CharField(
                default="", help_text="Cached client name for display", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="servicelead",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="assigned_to",
            field=models.CharField(
                blank=True,
                help_text="Employee ID from main auth service",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="created_by",
            field=models.CharField(
                help_text="User ID from main auth service", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client_id"], name="api_invoice_client__013ce8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="api_invoice_status_d10657_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["client_id"], name="api_quote_client__ce1eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="api_quote_status_c43222_idx"),
        ),
        migrations.AddIndex(
            model_name="servicelead",
            index=models.Index(
                fields=["client_id"], name="api_service_client__88c1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicelead",
            index=models.Index(fields=["status"], name="api_service_status_d30c59_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["client_id"], name="api_service_client__b35201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["order_status"], name="api_service_order_s_2b94cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(
                fields=["payment_status"], name="api_service_payment_bde23a_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
