# Generated by Django 5.2.9 on 2026-01-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_quote_client_remove_serviceorder_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("food", "Food"),
                            ("accommodation", "Accommodation"),
                            ("equipment", "Equipment"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(
                        help_text="Invoice reference e.g. FJ9387HDS",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("project_id", models.CharField(help_text="project", max_length=255)),
                ("budget_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Budget amount", max_digits=15
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("cheque", "Cheque"),
                        ],
                        default="transfer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-budget_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice_id"], name="api_budget_invoice_98a023_idx"
                    ),
                    models.Index(
                        fields=["project_id"], name="api_budget_project_9053fe_idx"
                    ),
                    models.Index(
                        fields=["status"], name="api_budget_status_7de34d_idx"
                    ),
                ],
            },
        ),
    ]
