# Generated by Django 5.2.6 on 2026-01-13 10:04

import api.models.event
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_expense_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("land", "Land"),
                        ],
                        max_length=50,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("rent", "For Rent"),
                            ("lease", "For Lease"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("location", models.TextField(verbose_name="Location/Address")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Price (₦)"
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Size (sqm)"
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                ("bathrooms", models.PositiveIntegerField(default=0)),
                ("parking_spaces", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("reserved", "Reserved"),
                            ("pending", "Pending"),
                            ("off_market", "Off Market"),
                        ],
                        default="available",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Owner"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Content title or headline",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog_post", "Blog Post"),
                            ("social_media", "Social Media"),
                            ("video", "Video"),
                            ("infographic", "Infographic"),
                            ("newsletter", "Newsletter"),
                            ("article", "Article"),
                        ],
                        default="blog_post",
                        max_length=50,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("website", "Website"),
                            ("medium", "Medium"),
                            ("youtube", "YouTube"),
                        ],
                        help_text="Platform where content is published",
                        max_length=50,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Main content/text",
                        verbose_name="Content Body",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short description or summary",
                        max_length=500,
                        verbose_name="Excerpt",
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(
                        blank=True, null=True, verbose_name="Featured Image"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times content was viewed",
                        verbose_name="Views",
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of likes/reactions",
                        verbose_name="Likes",
                    ),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times content was shared",
                        verbose_name="Shares",
                    ),
                ),
                (
                    "comments",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of comments",
                        verbose_name="Comments",
                    ),
                ),
                (
                    "author_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Author"
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when content was published",
                        null=True,
                        verbose_name="Published Date",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time to automatically publish",
                        null=True,
                        verbose_name="Scheduled Date",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL where content is published externally",
                        verbose_name="External URL",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO",
                        max_length=500,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Category"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured content",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="Allow Comments"),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Content",
                "ordering": ["-published_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_date"],
                        name="api_content_status_ec292a_idx",
                    ),
                    models.Index(
                        fields=["content_type", "platform"],
                        name="api_content_content_979cff_idx",
                    ),
                    models.Index(
                        fields=["author_id", "-created_at"],
                        name="api_content_author__24670d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or title of the event",
                        max_length=500,
                        verbose_name="Event Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the event",
                        verbose_name="Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("trade_show", "Trade Show"),
                            ("webinar", "Webinar"),
                            ("career_fair", "Career Fair"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("networking", "Networking"),
                            ("product_launch", "Product Launch"),
                            ("meetup", "Meetup"),
                            ("exhibition", "Exhibition"),
                        ],
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the venue or location",
                        max_length=255,
                        verbose_name="Venue Name",
                    ),
                ),
                (
                    "venue_address",
                    models.TextField(blank=True, verbose_name="Venue Address"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is an online/virtual event",
                        verbose_name="Online Event",
                    ),
                ),
                (
                    "online_platform",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Zoom, Google Meet, Microsoft Teams",
                        max_length=100,
                        verbose_name="Online Platform",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for online event",
                        verbose_name="Meeting URL",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="Event Date")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duration (Hours)",
                    ),
                ),
                (
                    "max_registrations",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of attendees allowed",
                        verbose_name="Maximum Registrations",
                    ),
                ),
                (
                    "current_registrations",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of people currently registered",
                        verbose_name="Current Registrations",
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Registration Deadline"
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Registration Fee",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, verbose_name="Allow Registration"
                    ),
                ),
                (
                    "organizer_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Organizer"
                    ),
                ),
                (
                    "team_members",
                    models.JSONField(
                        blank=True,
                        default=api.models.event.default_list,
                        verbose_name="Team Members",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Target Audience"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Event"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public events are visible to everyone",
                        verbose_name="Public Event",
                    ),
                ),
                (
                    "send_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send email reminders to registered attendees",
                        verbose_name="Send Reminders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["event_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "event_date"],
                        name="api_event_status_909a6f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-event_date"],
                        name="api_event_event_t_787d08_idx",
                    ),
                    models.Index(
                        fields=["organizer_id", "-created_at"],
                        name="api_event_organiz_db7a41_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the marketing campaign",
                        max_length=255,
                        verbose_name="Campaign Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the campaign target audience or purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("social_media", "Social Media"),
                            ("email", "Email"),
                            ("search", "Search"),
                            ("display", "Display"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Marketing Channel",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times the campaign was displayed",
                        verbose_name="Impressions",
                    ),
                ),
                (
                    "ctr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Click-through rate as a percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="CTR (%)",
                    ),
                ),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Return on Investment as a percentage",
                        max_digits=6,
                        verbose_name="ROI (%)",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Campaign completion percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progress (%)",
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budget allocated for the campaign",
                        max_digits=12,
                        verbose_name="Budget Allocated",
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount spent so far",
                        max_digits=12,
                        verbose_name="Budget Spent",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
            ],
            options={
                "verbose_name": "Marketing Campaign",
                "verbose_name_plural": "Marketing Campaigns",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_marketi_status_98ae3e_idx",
                    ),
                    models.Index(
                        fields=["channel"], name="api_marketi_channel_bfeb08_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendee_id",
                    models.CharField(max_length=50, verbose_name="Attendee"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Registration Status",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Confirmation Code",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="api.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registration_date"],
                "unique_together": {("event", "attendee_id")},
            },
        ),
    ]
